LocalSocket /tmp/clamd.sock
TCPSocket 3310
TCPAddr 0.0.0.0
TCPAddr ::
User clamav
DatabaseDirectory /var/lib/clamav
LogTime yes
MaxThreads 2
MaxQueue 4
StreamMaxLength 16M
MaxScanSize 32M
MaxFileSize 16M
MaxRecursion 8
MaxFiles 1000
AlertEncrypted yes
AlertExceedsMax yes
FailIfCvdOlderThan 7
BytecodeSecurity TrustSigned
EnableShutdownCommand no
ConcurrentDatabaseReload no
