export const en = {
  skip: "Skip to content",
  refresh: "Refresh",
  openNimiq: "Open in Nimiq Pay",
  checkingService: "Checking connection…",
  serviceUnavailable: "Unable to connect · retrying",
  sandboxStatus: "Demo mode · no real payments",
  testCheckoutStatus: "Test payments available",
  checkoutOffStatus: "Payments unavailable",
  requests: "Access requests",
  requestsHelp:
    "Approve clients who have requested access to your files. Check each wallet address with your client first.",
  reviewRequest: "Review request",
  settings: "Account settings",
  supportInbox: "Support requests",
  sessionAccess: "Your access",
  uploadAccess: "Create and manage handoffs",
  downloadAccess: "Purchased downloads only",
  fullAccess: "Full access",
  downloadOnly:
    "This desktop can only download purchases. To create handoffs, sign out and connect your wallet.",
  connectWorkspace: "Connect your wallet to see your handoffs",
  connectWorkspaceBody:
    "Sign in to manage your files, client requests, and payments.",
  loadingWorkspace: "Loading your workspace…",
  copyManually: "Copy this link to share it with your client.",
  deleteDraft: "Delete draft",
  deleteDraftHelp:
    "This permanently deletes the unpublished draft and its uploaded files.",
  draftDeleted: "Draft deleted",
  previewUnavailable: "Preview not ready",
  previewUnavailableBody:
    "This file needs to pass a security scan and have a preview before it can be shown.",
  removeFile: "Remove selected file",
  rescan: "Retry security scan",
  brand: "handoff",
  brandLabel: "FILE DELIVERY",
  deskWelcomeTitle: "Open your delivery desk.",
  deskWelcomeBody:
    "Bring the finished files. Give your client a preview. Keep the originals private until payment is verified.",
  deskKicker: "YOUR WORK, READY TO DELIVER",
  privateWorkspace: "Private workspace",
  welcomeLabel: "FINISHED WORK STARTS HERE",
  signInNote: "Signing in does not send money.",
  sequenceTitle: "THE HANDOFF SEQUENCE",
  sequenceNote: "One delivery. One intended client.",
  deliveryProgress: "Delivery progress",
  deskSteps: [
    [
      "Show the preview",
      "Approve a watermarked preview of the work your client will receive.",
    ],
    [
      "Verify the payment",
      "Payment is checked independently before original files unlock.",
    ],
    [
      "Release the originals",
      "Your approved client gets the exact files in the published delivery.",
    ],
  ],
  tagline: "Share files. Get paid.",
  workspace: "Your workspace",
  navigation: {
    awaiting: "Awaiting",
    ready: "To pay",
    pending: "In progress",
    requests: "Requests",
    support: "Support",
    settings: "Settings",
  },
  handoffs: "Handoffs",
  purchases: "Purchases",
  howItWorks: "How it works",
  builtFor: "Built for Nimiq Pay",
  wallet: "Connect wallet",
  signOut: "Sign out",
  welcome: "FILE DELIVERY",
  heroTitle: "Share your work.\nGet paid.",
  heroBody:
    "Let your client preview the work before paying. Original files stay private until payment is confirmed.",
  newHandoff: "New handoff",
  viewExample: "View example",
  heroNote: "You control who gets your files.",
  preview: "Preview",
  payment: "Payment",
  originals: "Originals",
  protected: "Originals stay private",
  sampleBanner: "Example workspace",
  sampleHelp:
    "These are sample projects. Connect your wallet to create your own.",
  development: "Preview mode · real payments are off",
  total: "Total handoffs",
  awaiting: "Awaiting client",
  drafts: "Drafts",
  projectsTitle: "Delivery desk",
  projectsSubtitle: "From your final edit to their final files.",
  all: "All handoffs",
  draft: "Draft",
  ready: "Ready for payment",
  search: "Search handoffs",
  newest: "Newest first",
  oldest: "Oldest first",
  grid: "Grid view",
  list: "List view",
  files: "files",
  noResults: "No handoffs found",
  noResultsBody: "Try a different search or create your first handoff.",
  clear: "Clear filters",
  client: "Client",
  for: "For",
  lastUpdated: "Created",
  open: "Open handoff",
  makeFirst: "Create your first handoff",
  makeFirstBody:
    "Add your files, set a price, and share a preview with your client.",
  createAnother: "New handoff",
  newCardBody: "Add files for another client or project.",
  connectTitle: "Sign in with your wallet",
  connectBody:
    "Choose the wallet you want to use, then approve the sign-in request. This does not send money.",
  connectNim: "Continue with NIM",
  connectUsdt: "Continue with Polygon USDT",
  connecting: "Check your wallet…",
  walletMissing: "Open Handoff inside Nimiq Pay to connect your wallet.",
  walletRejected:
    "Wallet connection was cancelled or could not be completed. Please try again.",
  networkError: "Could not reach Handoff. Please try again.",
  close: "Close",
  cancel: "Cancel",
  done: "Done",
  back: "Back to handoffs",
  newTitle: "New handoff",
  newSubtitle: "Add the project details, then upload your files.",
  titleLabel: "Project name",
  titlePlaceholder: "e.g. Website design",
  descriptionLabel: "What are you delivering?",
  descriptionPlaceholder: "Briefly describe the files you’re sending.",
  clientLabel: "Client name",
  clientPlaceholder: "e.g. Alex",
  currency: "Payment currency",
  amount: "Amount due",
  deadline: "Payment deadline",
  terms: "Usage and delivery terms",
  defaultTerms:
    "You can use these files as agreed once payment is confirmed. Message me with any questions.",
  termsHelp:
    "Explain how the client can use the files. Handoff cannot settle disputes or guarantee refunds.",
  saveDraft: "Save draft",
  saving: "Saving…",
  signInToSave: "Connect wallet to save",
  required: "Complete the required details before saving.",
  walletCurrency: "Currency is set by your connected wallet.",
  edit: "Edit details",
  editTitle: "Edit handoff",
  sample: "Example delivery",
  sampleNotice:
    "This is an example. No payment can be made and no originals are available.",
  delivery: "Your delivery",
  creator: "Receiving wallet",
  creatorLabelNote: "A wallet address does not confirm who someone is.",
  originalFiles: "Files",
  previewOnly: "Watermarked preview",
  previewExplain:
    "You can review the work here. The original files stay private.",
  paymentDisabled: "Payments unavailable",
  paymentDisabledBody:
    "Checkout is currently unavailable. Do not send payment manually.",
  termsTitle: "Usage and delivery terms",
  privateNote:
    "Previews can be saved or captured in screenshots. Original files stay private.",
  downloadWindow:
    "You have 30 days to download files after payment is confirmed. Unpaid files expire after the deadline.",
  creatorTools: "Prepare your delivery",
  addFiles: "Add original files",
  fileLimit:
    "Up to 10 files, 15 MB each. PDF previews show the first 3 pages; video previews show up to 12 seconds without sound. PSD, Blender and ZIP originals require a supplied preview.",
  uploading: "Preparing your preview…",
  noFiles: "Add your files",
  noFilesBody:
    "Upload a file to create a watermarked preview. For source files, add a separate image or PDF preview.",
  scanBlocked:
    "This file is blocked. It must pass a security scan before you can share it.",
  scanned: "Security scan passed",
  approved: "Preview approved",
  needsApproval: "Review this preview",
  approve: "I’ve reviewed every preview",
  publish: "Publish preview link",
  publishing: "Publishing…",
  publishHelp:
    "Once published, you cannot change the files, price, terms, or deadline. Only your approved client can pay when test payments are available.",
  share: "Copy share link",
  copied: "Link copied",
  invite: "Client access",
  inviteHelp:
    "Your client can request access after opening this link. Check their wallet address before approving.",
  noRequests: "No client requests yet.",
  approveWallet: "Approve this wallet",
  boundWallet: "Approved client wallet",
  bindTitle: "Approve this client?",
  bindHelp:
    "Check this wallet address with your client first. You cannot change the approved wallet later.",
  accessApproved: "Your wallet is approved for this delivery.",
  accessBound:
    "This delivery is assigned to another wallet. Connect the approved wallet to continue.",
  signInForAccess:
    "Connect the approved client wallet to access this delivery.",
  requestAccess: "Request access with my wallet",
  requestSent: "Access requested. Ask the creator to approve your wallet.",
  approvalHint:
    "Connect your wallet and request access. The creator must approve your wallet before you can pay.",
  expired: "This handoff is unavailable or has expired.",
  loading: "Loading your handoff…",
  purchasesTitle: "Your purchases",
  purchasesBody: "Find your paid deliveries and download your files.",
  purchasesEmpty: "No purchases yet",
  purchasesHelp:
    "Have a delivery link? Open it to review the work and request access.",
  howTitle: "How Handoff works",
  howSteps: [
    [
      "Add your files",
      "Upload your files and check the watermarked previews. Original files stay private.",
    ],
    ["Share the preview", "Set the price and send your client the link."],
    [
      "Payment unlocks the files",
      "Handoff checks that payment is confirmed on the network before the client can download the original files.",
    ],
  ],
  howNote:
    "Payments are only available on supported networks when checkout is enabled. Always follow the checkout instructions.",
  support: "Need help?",
  supportBody:
    "For changes to the work, payment questions, or refunds, message the creator directly.",
} as const;
