export const en = {
  skip: "Skip to content",
  pilot: "PILOT BUILD",
  removeFile: "Remove selected file",
  rescan: "Retry malware scan",
  brand: "handoff",
  tagline: "Good work deserves a great handoff.",
  workspace: "Your workspace",
  handoffs: "My handoffs",
  purchases: "Purchases",
  howItWorks: "How it works",
  builtFor: "Built for Nimiq Pay",
  wallet: "Connect wallet",
  signOut: "Sign out",
  welcome: "THE FINAL STEP, SIMPLIFIED",
  heroTitle: "Your work.\nOn your terms.",
  heroBody:
    "A beautiful preview. A clear price. Your originals stay private until payment is verified.",
  newHandoff: "New handoff",
  viewExample: "Explore an example",
  heroNote: "Made for the work you put your name on.",
  preview: "Preview",
  payment: "Payment",
  originals: "Originals",
  protected: "Originals stay private",
  sampleBanner: "Example workspace",
  sampleHelp:
    "These are sample projects. Connect your wallet to create your own.",
  development: "Development preview · Live payments are not enabled",
  total: "Total handoffs",
  awaiting: "Awaiting client",
  drafts: "Drafts",
  projectsTitle: "All your finishing touches.",
  projectsSubtitle: "Prepare, preview, and share your next delivery.",
  all: "All handoffs",
  draft: "Draft",
  ready: "Ready for payment",
  search: "Search handoffs",
  newest: "Newest first",
  oldest: "Oldest first",
  grid: "Grid view",
  list: "List view",
  files: "files",
  noResults: "No handoffs found",
  noResultsBody: "Try a different search or create your first handoff.",
  clear: "Clear filters",
  client: "Client",
  for: "For",
  lastUpdated: "Created",
  open: "Open handoff",
  makeFirst: "A little work. A big handoff.",
  makeFirstBody:
    "Bring the files. We’ll help you put the finishing touch on delivery.",
  createAnother: "Start something new",
  newCardBody: "Turn finished work into your next handoff.",
  connectTitle: "Your wallet is your sign-in.",
  connectBody:
    "Choose a wallet to prove ownership of your receiving address. Signing in does not send money.",
  connectNim: "Continue with NIM",
  connectUsdt: "Continue with Polygon USDT",
  connecting: "Check your wallet…",
  walletMissing: "Open Handoff inside Nimiq Pay to connect your wallet.",
  walletRejected:
    "Wallet connection was cancelled or could not be completed. Please try again.",
  networkError: "Could not reach Handoff. Please try again.",
  close: "Close",
  cancel: "Cancel",
  done: "Done",
  back: "Back to handoffs",
  newTitle: "Let’s wrap up the good work.",
  newSubtitle:
    "Start with the details. You can add files and review previews next.",
  titleLabel: "Project title",
  titlePlaceholder: "e.g. Olive Studio brand identity",
  descriptionLabel: "What are you delivering?",
  descriptionPlaceholder:
    "Give your client a little context about the final work.",
  clientLabel: "Client name or label",
  clientPlaceholder: "e.g. Alex at Olive Studio",
  currency: "Payment currency",
  amount: "Outstanding balance",
  deadline: "Payment deadline",
  terms: "License and delivery terms",
  defaultTerms:
    "The agreed usage rights transfer after payment. Contact me in our existing conversation with any questions about this delivery.",
  termsHelp:
    "Describe the agreed usage rights. Handoff does not arbitrate disputes or guarantee refunds.",
  saveDraft: "Save draft",
  saving: "Saving…",
  signInToSave: "Connect wallet to save",
  required: "Complete the required details before saving.",
  walletCurrency: "The currency follows your connected payout wallet.",
  edit: "Edit details",
  editTitle: "Fine-tune the details.",
  sample: "EXAMPLE DELIVERY",
  sampleNotice:
    "This is an example. No payment can be made and no originals are available.",
  delivery: "YOUR DELIVERY",
  creator: "Receiving wallet",
  creatorLabelNote: "A wallet address is not a verified legal identity.",
  originalFiles: "What’s inside",
  previewOnly: "Watermarked preview",
  previewExplain:
    "You can review the work here. The original files stay private.",
  paymentDisabled: "Payments are coming next",
  paymentDisabledBody:
    "Checkout is not available in this development build. Do not send payment manually.",
  termsTitle: "The details, agreed.",
  privateNote:
    "Previews can be captured or saved. Only the original file bytes are kept private.",
  downloadWindow:
    "Downloads remain available for 30 days after payment verification. Unpaid files expire after the deadline.",
  creatorTools: "Prepare your delivery",
  addFiles: "Add original images",
  fileLimit:
    "Up to 10 files, 15 MB each. PDF previews show the first 3 pages; video previews show up to 12 seconds without sound. PSD, Blender and ZIP originals require a supplied preview.",
  uploading: "Preparing your preview…",
  noFiles: "Your work goes here.",
  noFilesBody:
    "Upload an original to create a separate, watermarked preview. Source files need a supplied image or PDF preview.",
  scanBlocked:
    "This file is quarantined. A clean malware scan is needed before it can be shared.",
  scanned: "Malware scan passed",
  approved: "Preview approved",
  needsApproval: "Review this preview",
  approve: "I’ve reviewed every preview",
  publish: "Publish preview link",
  publishing: "Publishing…",
  publishHelp:
    "Publishing freezes the files, price, terms, and deadline. Only the approved client can pay when test checkout is configured.",
  share: "Copy share link",
  copied: "Link copied",
  invite: "Client access",
  inviteHelp:
    "The client opens your link and requests access with their wallet. Approve only the wallet you expect.",
  noRequests: "No client requests yet.",
  approveWallet: "Approve this wallet",
  boundWallet: "Approved client wallet",
  bindTitle: "Approve this client?",
  bindHelp:
    "Check this address with your client in your existing conversation. It cannot be replaced after approval.",
  requestAccess: "Request access with my wallet",
  requestSent: "Access requested. Ask the creator to approve your wallet.",
  approvalHint:
    "Connect your wallet and request access. The creator must approve your wallet before checkout can be enabled.",
  expired: "This handoff is unavailable or has expired.",
  loading: "Loading your handoff…",
  purchasesTitle: "The work you’ve made yours.",
  purchasesBody:
    "Your paid deliveries will appear here once payments are available.",
  purchasesEmpty: "Nothing to unpack just yet.",
  purchasesHelp:
    "Have a delivery link? Open it to review the work and request access.",
  howTitle: "A better last step.",
  howSteps: [
    [
      "Prepare the work",
      "Upload your originals and check the watermarked previews. Your files stay private.",
    ],
    [
      "Share the preview",
      "Set the agreed balance and send your client a delivery link in your existing conversation.",
    ],
    [
      "Get paid. Hand it over.",
      "Once payment verification is live, finalized payment will unlock the exact original files.",
    ],
  ],
  howNote:
    "This build supports preparation and previews. Live payments and downloads are still being developed.",
  support: "Keep the conversation going",
  supportBody:
    "For revisions, payment questions, or refund requests, contact the creator in your existing conversation.",
} as const;
