export const workflow = {
  sessionChanged:
    "Your sign-in changed. Open this delivery again before paying.",
  invalidIntent:
    "The payment details are invalid. Refresh this delivery before paying.",
  expiredIntent:
    "The payment deadline has passed. Check payment status before contacting the creator.",
  walletOnly: "Approve the payment in your phone’s wallet.",
  retryWallet: "Open wallet again",
  retryHelp:
    "Check your wallet history first. Only try again if you cancelled or no payment was sent.",
  openInWallet: "Open in Nimiq Pay",
  approved: "Desktop approved. Return to the desktop to finish pairing.",
  noDevices: "No paired desktops for this wallet.",
  signInPurchases:
    "Connect your wallet or pair this desktop to see your purchases.",
  viewDelivery: "View delivery",
  downloading: "Preparing download…",
  requestHistory: "Saved requests",
  noRequests: "No support requests yet.",
  openRequest: "Open",
  resolvedRequest: "Resolved",
  refundReference: "Refund transaction",
  receiptAmount: "Amount paid",
  payer: "Paid by",
  recipient: "Paid to",
  paidAt: "Payment date",
  pendingAccess: "Waiting for the creator to approve your wallet.",
  purchaseSearch: "Search purchases",
  noMatches: "No purchases match your search.",
  playPreview: "Play short preview",
  pausePreview: "Pause preview",
  switchTestnet: "Switch Nimiq Pay to testnet before paying.",
  networkCheckUnavailable:
    "Handoff couldn't check the test network. Reopen this delivery in Nimiq Pay's test mode and try again.",
  approvedWallet: "Use the approved client wallet.",
  openWallet: "Open this delivery in Nimiq Pay.",
  paidStatus: "Paid",
  pendingStatus: "Payment started",
  pair: "Pair a desktop",
  upload: "Upload and prepare deliveries",
  download: "Download purchases",
  createPair: "Create pairing code",
  pairHelp:
    "This code expires in five minutes. Open the link on your phone and sign in. Check the website address, access level, and matching phrase before approving. Scanning the code alone does not give access.",
  phrase: "Matching phrase",
  approve: "Approve this desktop",
  waiting: "Waiting for phone approval…",
  paired: "Desktop paired for one hour.",
  expired: "This pairing has expired. Create a new code.",
  devices: "Paired desktops",
  revoke: "Remove access",
  signIn: "Sign in with your wallet on the phone to approve.",
  role: "Desktop access",
  origin: "Website address",
  error: "Something went wrong. Try again.",
  demo: "Demo mode uses test accounts and pretend payments. No money is sent. Files still need to pass a security scan.",
  demoCreator: "Demo creator",
  demoClient: "Demo client",
  pay: "Make test payment",
  simulate: "Try demo payment",
  confirming:
    "Checking that payment is confirmed on the network. You can close this page and return later.",
  approval: "Review and approve in your wallet…",
  sent: "Payment sent. Handoff is checking it on the network.",
  recover: "Check payment status",
  receipt: "Payment receipt",
  paid: "Payment verified",
  expiredDownload: "The download period has ended.",
  downloadOriginal: "Download original",
  retention: "Downloads available until",
  access: "Download requests",
  noAccess: "No original download requests yet.",
  testOnly:
    "Test payments only. Do not send real money or pay this address manually.",
  fees: "Payment goes straight to the creator. Handoff charges no fee. Your wallet shows any network fee before you approve.",
  unavailable: "Test payments are currently unavailable.",
  clientApproval:
    "Your wallet must be approved by the creator before checkout.",
  purchases: "Your purchases",
  empty: "No verified purchases for this wallet yet.",
  loading: "Loading…",
  support: "Help or refund request",
  supportNote:
    "Refunds are arranged directly with the creator. Handoff cannot reverse a payment. A request does not guarantee a refund.",
  sendRequest: "Save support request",
  saved:
    "Request saved. Contact the creator in your existing conversation and share this delivery link.",
  kind: "Request type",
  message: "What happened?",
  accessIssue: "File access",
  refund: "Refund",
  other: "Other",
  supplied: "Upload an image or PDF preview",
  suppliedRequired: "Add a preview before publishing.",
  refresh: "Refresh",
};
