export const workflow = {
  sessionChanged:
    "Your wallet session changed. Open this delivery again before paying.",
  invalidIntent:
    "The payment details are invalid. Refresh this delivery before paying.",
  expiredIntent:
    "The payment deadline has passed. Check payment status before contacting the creator.",
  walletOnly: "Approve payment from your wallet session on your phone.",
  retryWallet: "Open wallet again",
  retryHelp:
    "Check your wallet history first. Only try again if you cancelled or no payment was sent.",
  openInWallet: "Open in Nimiq Pay",
  approved: "Desktop approved. Return to the desktop to finish pairing.",
  noDevices: "No paired desktops for this wallet.",
  signInPurchases:
    "Connect your wallet or pair this desktop to see your purchases.",
  viewDelivery: "View delivery",
  downloading: "Preparing download…",
  requestHistory: "Saved requests",
  noRequests: "No support requests yet.",
  openRequest: "Open",
  resolvedRequest: "Resolved",
  refundReference: "Refund transaction",
  receiptAmount: "Amount paid",
  payer: "Paid by",
  recipient: "Paid to",
  paidAt: "Payment date",
  pendingAccess: "Waiting for the creator to approve your wallet.",
  purchaseSearch: "Search purchases",
  noMatches: "No purchases match your search.",
  playPreview: "Play short preview",
  pausePreview: "Pause preview",
  switchTestnet: "Switch Nimiq Pay to testnet before paying.",
  approvedWallet: "Use the approved client wallet.",
  openWallet: "Open this delivery in Nimiq Pay.",
  paidStatus: "Paid",
  pendingStatus: "Payment started",
  pair: "Pair a desktop",
  upload: "Upload and prepare deliveries",
  download: "Download purchases",
  createPair: "Create a five-minute pairing code",
  pairHelp:
    "Open this link in your signed-in phone. Check the origin, role and matching phrase before approving. Scanning alone grants no access.",
  phrase: "Matching phrase",
  approve: "Approve this desktop",
  waiting: "Waiting for phone approval…",
  paired: "Desktop paired for one hour.",
  expired: "This pairing has expired. Create a new code.",
  devices: "Paired desktops",
  revoke: "Revoke access",
  signIn: "Sign in with your wallet on the phone to approve.",
  role: "Desktop access",
  origin: "Site origin",
  error: "Something went wrong. Try again.",
  demo: "LOCAL SANDBOX — simulated identities and payments. No money moves. Malware screening remains required.",
  demoCreator: "Demo creator",
  demoClient: "Demo client",
  pay: "Pay on testnet",
  simulate: "Simulate demo payment",
  confirming:
    "Checking the chain for finalized payment. You can close this page and return later.",
  approval: "Review and approve in your wallet…",
  sent: "Payment sent. Waiting for independent verification.",
  recover: "Check payment status",
  receipt: "Payment receipt",
  paid: "Payment verified",
  expiredDownload: "The download period has ended.",
  downloadOriginal: "Download original",
  retention: "Downloads available until",
  access: "Download requests",
  noAccess: "No original download requests yet.",
  testOnly:
    "Test networks only. Do not send real money or pay this address manually.",
  fees: "Payment goes directly to the creator. Handoff adds no platform fee; the wallet shows network fees before approval.",
  unavailable:
    "Checkout is disabled until test-network verification is configured.",
  clientApproval:
    "Your wallet must be approved by the creator before checkout.",
  purchases: "Your purchases",
  empty: "No verified purchases for this wallet yet.",
  loading: "Loading…",
  support: "Help or refund request",
  supportNote:
    "Refunds are arranged directly with the creator. Handoff cannot reverse a payment. A request does not guarantee a refund.",
  sendRequest: "Save support request",
  saved:
    "Request saved. Contact the creator in your existing conversation and share this delivery link.",
  kind: "Request type",
  message: "What happened?",
  accessIssue: "File access",
  refund: "Refund",
  other: "Other",
  supplied: "Upload an image or PDF preview",
  suppliedRequired:
    "A creator-supplied preview is required before publication.",
  refresh: "Refresh",
};
